### ISSUE TITLE
알고리즘 파트 합병 정렬 (Merge Sort) 시간 복잡도 오류

### ISSUE THREAD

**Issue by dsmMinseo** [Prev/CSE-Summary#1]
알고리즘 파트의 합병 정렬 설명 중 시간 복잡도가 O(n^2)로 적혀있습니다.
합병 정렬은 divide 시 O(log n), merge 시 O(n)이 걸려 O(n log n)입니다.

**Comment by Prev** [comment]
오류 제보 감사드립니다!

수정하였습니다.
